#/appspec.yml
version: 0.0
os: linux
files:
  - source: /
    destination: /deploy
hooks:
  AfterInstall:
    - location: Scripts/pullDocker.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: Scripts/runDocker.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: Scripts/stopDocker.sh
      timeout: 60
      runas: root
